### ISSUE TITLE
need help with loop of regressions 

### ISSUE THREAD

**Issue by VasilevaDO** [amicha02/ape_mining#21]
looping over regressors, to compare models performance...someone help? 
look in [2.0-dv-ols-forest.ipynb](http://localhost:8889/notebooks/Desktop/ape_mining/notebooks/2.0-dv-ols-forest.ipynb)

**Comment by mwander000** [comment]
I fixed it using a dictionary to hold the predictions and scores, and a zip of model names and model objects in 5.0-mw-Combine_Models_Predictions
